Fueled/django-init

{{cookiecutter.github_repository}}/fabfile.py
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/production.txt
{{cookiecutter.github_repository}}/settings/testing.py

* Update to use new get_cli_string in fab for dotenv.
* Remove used test setting

Upgrade to Django 1.8.6

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/production.txt

Also, updated the following to:
- whitenoise==2.0.6
- django-versatileimagefield==1.1
- ipython==4.0.1
- django-redis==4.3.0
- gunicorn==19.4.1

Update django to 1.8.7 [security release]

---

CHANGELOG.md
{{cookiecutter.github_repository}}/.travis.yml
{{cookiecutter.github_repository}}/bin/post_compile
{{cookiecutter.github_repository}}/docs/backend/server_config.md
{{cookiecutter.github_repository}}/requirements/common.txt

- It's faster than running from travis
- It's is always run even deployment is triggered from local cli
- DRY!

Use `/bin/post_compile` to run migration and deployment checks

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.conf.j2

- use `service nginx reload` instead of `restart` whenever possible
- remove `/var/www` as root (not required)
- remove upstream @app_server declaration

fix(ansible/nginx): remove unnecessary declarations

---

CHANGELOG.md
README.md
cookiecutter.json
{{cookiecutter.github_repository}}/.travis.yml
{{cookiecutter.github_repository}}/README.md
{{cookiecutter.github_repository}}/docs/backend/server_config.md
{{cookiecutter.github_repository}}/provisioner/roles/common/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/common/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/postgresql/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/postgresql/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/vars.yml
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/production.py

Now we ask if postgis should be supported and install postgis libraries
accordingly. Added better postgresql apt repository so that we can
get v9.5 or v9.6 instead of ubuntu trusty's default 9.3
Also added a question for python version for ansible provisioner.

feat(ansible/postgresql): Add postgis support for postgresql role

---

{{cookiecutter.github_repository}}/provisioner/roles/celery/handlers/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/celery/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/postgresql/handlers/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/postgresql/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/redis/handlers/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/supervisor/handlers/main.yml
{{cookiecutter.github_repository}}/provisioner/site.yml

Ansible suggests using `become` instead of `sudo`

Update ansible commands which were giving warnings

---

{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/templates/admin/base_site.html

- Puts default project name in login and header of admin pages

feat(admin/template): Add admin base template

---

{{cookiecutter.github_repository}}/.travis.yml
{{cookiecutter.github_repository}}/fabfile.py
{{cookiecutter.github_repository}}/provisioner/vars.yml

- Make sure `fab init` respects python3 settings
- Use Python3 in travis

Improve overall python3 support

---

{{cookiecutter.github_repository}}/CONTRIBUTING.md
{{cookiecutter.github_repository}}/requirements/common.txt

Also changed a link to django docs to use stable redirection uri

Upgrade to django 1.9.4 [security release]

---

{{cookiecutter.github_repository}}/setup.cfg
{{cookiecutter.github_repository}}/tests/conftest.py

- remove unnecessary boilerplate code which is not required in latest pytest-django

fix(test): while running tests use 'settings.testing' module

---

{{cookiecutter.github_repository}}/docs/api/errors.md
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/exceptions.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/views.py

Need feedback on this; especially language in `errors.md`.

feat(base/exceptions): Change how custom exception handler display error

---

{{cookiecutter.github_repository}}/requirements/common.txt

https://docs.djangoproject.com/en/1.9/releases/1.9.5/
https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#320-2016-04-01

Update to django 1.9.5 and pillow 3.2.0 to latest

---

CHANGELOG.md
{{cookiecutter.github_repository}}/.coveragerc
{{cookiecutter.github_repository}}/setup.cfg

- One less at root_dir
- Add config to display missing lines in coverage

chore(coverage.py): Move .coveragerc config to setup.cfg

---

CHANGELOG.md
README.md
cookiecutter.json
{{cookiecutter.github_repository}}/provisioner/hosts
{{cookiecutter.github_repository}}/provisioner/roles/common/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/letsencrypt.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.443.conf.j2
{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.80.conf.j2
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/vars.yml

feat(add_letsencrypt): add lets encrypt

---

CHANGELOG.md
README.md
cookiecutter.json
hooks/post_gen_project.sh
{{cookiecutter.github_repository}}/bin/post_compile
{{cookiecutter.github_repository}}/docs/backend/server_config.md
{{cookiecutter.github_repository}}/package.json
{{cookiecutter.github_repository}}/provisioner/roles/nodejs/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/meta/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/vars.yml
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/production.py
{{cookiecutter.github_repository}}/settings/testing.py
{{cookiecutter.github_repository}}/wsgi.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/templates/base.html

feat(sass): Add sass and django compressor

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/production.txt
{{cookiecutter.github_repository}}/settings/development.py
{{cookiecutter.github_repository}}/settings/production.py
{{cookiecutter.github_repository}}/settings/testing.py

Major updates:
flake8==3.0.4
Others are just bug fixes

Update third-party requirement to latest

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/views.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/templates/403_csrf.html
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/urls.py

- update django
- Add logger for 'django.server'
- Remove django-model-utils
closes #177

Upgrade to Django 1.10.x

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/production.txt

Didn't upgrade DRF, it will come in another PR.

Update requirements to latest stable.

---

cookiecutter.json
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/production.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/context_processors.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/templates/base.html

Sentry is a real time error tracking system that alert you for any crashes as soon as it occurs.
Provides configurations for adding sentry to a Django app. 
None as of now.

feat(sentry): Add sentry support.

---

CHANGELOG.md
cookiecutter.json
{{cookiecutter.github_repository}}/docs/backend/server_config.md
{{cookiecutter.github_repository}}/requirements/production.txt
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/production.py

Ref: https://github.com/theskumar/django-auth-wall

Add staging site protection with Basic Auth

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.80.conf.j2

Fixed Nginx Configuration to run on vagrant with uwsgi.

fix(nginx): Fix vagrant nginx file

---

{{cookiecutter.github_repository}}/provisioner/roles/common/files/bashrc
{{cookiecutter.github_repository}}/provisioner/roles/common/tasks/main.yml

Add PS1 to display fqdn & set hostname via ansible

---

README.md

add your text here...
add your text here...
add your text here...

Minor Typo fix.

---

{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/production.py
{{cookiecutter.github_repository}}/wsgi.py

fix(settings): Fix flake8 issues with wsgi and settings

---

cookiecutter.json
hooks/post_gen_project.sh
{{cookiecutter.github_repository}}/Procfile
{{cookiecutter.github_repository}}/README.md
{{cookiecutter.github_repository}}/fabfile.py
{{cookiecutter.github_repository}}/provisioner/site.yml
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/__init__.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/celery.py

We make mistakes while configuring celery
add celery configuration as optional
no

feat(celery): add celery configuration

---

CHANGELOG.md
{{cookiecutter.github_repository}}/requirements/production.txt
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/development.py
{{cookiecutter.github_repository}}/settings/production.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/urls.py

1. new-style middleware
2. admin url include
3. see individual commits for more info
closes #222

Fix depreciation warnings - RemovedInDjango20Warning

---

{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml

Log SHA of last and new commit being deployed by ansible provisioner

---

CHANGELOG.md
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/api/mixins.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/schemas.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/templates/rest_framework_swagger/index.html
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/urls.py

Add django-rest-swagger integration

---

CHANGELOG.md
cookiecutter.json
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/development.py
{{cookiecutter.github_repository}}/settings/production.py

Frontend not able to test api on their local servers.
Add handling of server headers required for Cross-Origin Resource Sharing (CORS)
No

feat(cors): add `django-cors-headers` integration

---

{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/api/mixins.py

Earlier version was exact copy from `stackoverflow`. It comes under cc-by-sa licence  which might conflict with commercial softwares.
Written our own version of code.
No

fix(base): update multi serializer mixin

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.443.conf.j2

site had B+ rating on ssllabs.com
fixes the issues and gets the site an A rating on ssllabs.
web app stops working on Internet Explorer 6

enhance security by disabling deprecated ciphers

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.443.conf.j2

- Enable accepted ciphers
- Enable ssl_session
- Enable OCSP Stapling

feat(nginx): Add security improvements for ssl.

---

{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/templates/pages/about.html
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/templates/pages/home.html

Typo's were viewable on homepage
It simply fixes the typo's
None.

fix(pages) Fix typos: comming > coming

---

{{cookiecutter.github_repository}}/package.json

Upgrade to latest dependencies
Need to test this once.

Upgrade node dependencies

---

{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/routers.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/services.py

Routers for recently added JWT tokens were not added in the previous PR. So the tests are failing.
Fixes Auth tests.
None.

fix(auth): Fix routers and services

---

CHANGELOG.md
README.md
{{cookiecutter.github_repository}}/.travis.yml
{{cookiecutter.github_repository}}/circle.yml
{{cookiecutter.github_repository}}/provisioner/roles/common/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/common/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml
{{cookiecutter.github_repository}}/runtime.txt

Python 3.6 is the latest stable version of Python and Django has official support for it as well.
Uses python3.6 every platform
Nope

feat(system): upgrade from python 3.5.x to python 3.6.x

---

CHANGELOG.md
{{cookiecutter.github_repository}}/settings/common.py

The default configurations of swagger doesn't work with the current setup of the project.
Add sensible settings
Nope.

Add swagger settings, as per current drf configuration

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/production.txt

- remove pytest-pythonpath, it's no longer needed

Update all the requirements to latest stable

---

CHANGELOG.md
README.md
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/api/routers.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/auth/api.py

- Upgrade minor versions for django and other utility packages.
- updates changelog and readme
To move with the changing times. DRF 3.8.x introduced a couple of breaking changes in how you could add more actions to a viewset.
Upgrades requirements and gets rid of soon to be deprecated code.
No side effects with regards to functionality we get after scaffolding.

feat(system) - Upgrade to Django Rest Framework 3.8.x

---

CHANGELOG.md
README.md
cookiecutter.json
{{cookiecutter.github_repository}}/provisioner/roles/nginx/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/htpasswd.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.443.conf.j2

Currently, the docs are publically available.
Adds htpasswd based authentication scheme
Yes.

feat(provisioner) - password protect the project documentation

---

{{cookiecutter.github_repository}}/settings/production.py

Minor spell fix in the variable name.
Fixes the spelling.
None.

fix(settings/production): Minor spell fix

---

{{cookiecutter.github_repository}}/settings/production.py

Minor spell fix in the variable name.
Fixes the spelling.
None.

fix(common/production): Fix spelling for assets

---

{{cookiecutter.github_repository}}/fabfile.py
{{cookiecutter.github_repository}}/settings/production.py
{{cookiecutter.github_repository}}/settings/testing.py
{{cookiecutter.github_repository}}/tests/conftest.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/serializers.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/services.py

To sort imports correctly
Sort import statements correctly across the codebase.
None

fix(*): Sort-import statements

---

.travis.yml
{{cookiecutter.github_repository}}/.travis.yml
{{cookiecutter.github_repository}}/provisioner/roles/postgresql/tasks/main.yml

Upgrade Postgres to 10 and postgis to 2.4
By Upgrading Postgres
None.

chore(*): Upgrade Postgres to 10 and PostGIS to 2.4

---

CHANGELOG.md
README.md
{{cookiecutter.github_repository}}/README.md

Update docs for Postgres and PostGIS version upgrades.
Updating the docs
None.

Update docs for Postgres and PostGIS updates

---

README.md
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/production.txt
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/auth/utils.py

Keeping it upto date + security fixes
python dependencies updated to their latest stable.
nope

Update requirements to their latest, Django 2.2.x

---

{{cookiecutter.github_repository}}/.pre-commit-config.yaml

Making whitespace consistent for indentation
Makes whitespace consistent
None.

fix(pre-commit-config.yml): Minor indentation fixes

---

{{cookiecutter.github_repository}}/docs/backend/coding_rules.md

To fix the Markdown format for lists
Fixes the lists so that it is rendered correctly
None

fix(coding_rules): Fix formatting for rules for field lists

---

.travis.yml
CHANGELOG.md
README.md
{{cookiecutter.github_repository}}/.travis.yml
{{cookiecutter.github_repository}}/README.md
{{cookiecutter.github_repository}}/provisioner/roles/common/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/common/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/uwsgi-setup.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/templates/django.uwsgi.ini.j2
{{cookiecutter.github_repository}}/runtime.txt

To keep the stack upto date, and enable uses of new features and fixes of python.
Not that I know.

feat(): upgrade from python 3.6 to python 3.7

---

{{cookiecutter.github_repository}}/requirements/common.txt

GH pointed out the security vulnerability in pillow
updates to the version suggested
No.

chore - update pillow due to security vulnerability

---

{{cookiecutter.github_repository}}/docs/api/1-auth.md

Update docs for registration API changes; accepting `first_name` and `last_name`
Update the docs.
None.

docs(auth): Update user registration API docs

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/docs.txt
{{cookiecutter.github_repository}}/requirements/production.txt

To keep this project updated and bug free.
update project depencies.
No.

feat: upgrade python dependencies to latest stable

---

CHANGELOG.md
{{cookiecutter.github_repository}}/.env.sample
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/docs.txt
{{cookiecutter.github_repository}}/requirements/production.txt
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/development.py
{{cookiecutter.github_repository}}/settings/production.py

To keep dependencies upto date.
upgrade dependencies 
No.
Django is not upgraded to 3.1.x yet as it will need some more testing.

update dependencies to latest

---

{{cookiecutter.github_repository}}/docs/backend/api_mixins.md
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/api/mixins.py

Its a useful addition to the api mixins we already have on the project.
No.

feat(*) - add api mixin for permission per action on drf viewsets

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt

Various python dependencies are outdated.
Update python dependencies to latest stable.
None.

Update python dependencies

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/docs.txt
{{cookiecutter.github_repository}}/requirements/production.txt
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/auth/tokens.py

django & pillow have been updated due to security vulnerability

Update python dependencies to their latest

---

{{cookiecutter.github_repository}}/provisioner/hosts

Just a clean up for the ansible host file
Putting up the common settings in [all] section
not as of now.

chore: cleanup ansible host file

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/docs.txt
{{cookiecutter.github_repository}}/requirements/production.txt

Django is not upgraded from 3.1 to 3.2 yet.

Upgrade python libraries to their latest except Django

---

README.md
{{cookiecutter.github_repository}}/pyproject.toml

Upgrade packages to keep them up to date
Keep packages up-to-date
None

fix: upgrade packages
