{{cookiecutter.github_repository}}/settings/production.py

OrdinaryCallingFormat throws the following error while running
collectstatic, switching back to default calling format fixes the issues.
Also, removed AWS_AUTO_CREATE_BUCKET=True settings, the bucket must be
created manually with proper settings.
Error Trackback:
```
execute_from_command_line(sys.argv)
File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 343, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
self.execute(*args, **cmd_options)
File …
```

fix(settings/boto): switch to default AWS_S3_CALLING_FORMAT

---

{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/models.py

We are using Versatileimage field to store image in this mixin. Also uuid_upload_to determines to path by creating a uuid for that file.

feat(base/models): add image mixin to base models

---

CHANGELOG.md
{{cookiecutter.github_repository}}/docs/backend/server_config.md
{{cookiecutter.github_repository}}/settings/production.py

The email settings is no longer smtp server dependent.
closes #87 #84

refractor(email/smtp): switch to mailgun as SMTP server (heroku only)

---

{{cookiecutter.github_repository}}/requirements/production.txt

We are not using gevent in this project. It should be up-to developer to add it if needed.

chore(settings): Remove gevent library for production environments

---

CHANGELOG.md
{{cookiecutter.github_repository}}/settings/production.py

Simple `cache` may cause non-persistent sessions, use `cache_db` as a safe
option. This uses a write-through cache – every write to the cache will
also be written to the database.
Should be changed to direct `django.contrib.sessions.backends.cache`,
while doing performance review, if necessary.
Read more: https://docs.djangoproject.com/en/1.8/topics/http/sessions/#using-cached-sessions

feat(settings): use `cache_db` as `SESSION_ENGINE` instead of simple `cache`

---

CHANGELOG.md
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/production.py

- all functionalities of `django-secure` has now been integrated in django.
- move some settings to common, as they should be present during development
to in-order to catch any issue.
- in production, enable `https` sepecific settings only when site is set to run
over `https`

feat(settings): use in-built `SecurityMiddleware` instead of django-secure

---

CHANGELOG.md
{{cookiecutter.github_repository}}/settings/common.py

- use `DJANGO_ADMIN_EMAIL` as variable name
closes #97

feat(settings): Allow ADMIN_EMAIL to be set via environment variable

---

CHANGELOG.md
{{cookiecutter.github_repository}}/settings/production.py

- RedisToGo on heroku supports maximum of 10 connections

feat(settings): Add `REDIS_MAX_CONNECTIONS` parameter with default reduced to 10.

---

cookiecutter.json
{{cookiecutter.github_repository}}/provisioner/hosts
{{cookiecutter.github_repository}}/provisioner/roles/celery/templates/supervisor_celery.conf.j2
{{cookiecutter.github_repository}}/provisioner/roles/common/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/common/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.conf.j2
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/templates/env.env.j2
{{cookiecutter.github_repository}}/provisioner/roles/project_data/templates/supervisor_gunicorn.conf.j2
{{cookiecutter.github_repository}}/provisioner/vars.yml
{{cookiecutter.github_repository}}/requirements/development.txt

Vagrant ansible provisioner is now running with Django's development
settings. Changed the cookiecutter python_version question to python3.
For now, we are using nginx, supervisor and gunicorn in vagrant as well.
For consistency among various python packages, custom postgis and python3 version, I am adding custom ppa for python3.5.

fix(vagrant/provisioner): Make ansible provisioner run in vagrant

---

CHANGELOG.md
{{cookiecutter.github_repository}}/docs/backend/server_config.md
{{cookiecutter.github_repository}}/settings/production.py

- Use `REDIS_URL` instead of `REDISTOGO_URL` url.
closes #124

Replace redistogo with heroku-redis on Heroku

---

{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/utils/pagination.py

- Allow passing extra context variables to `serializer_class`.
Currently it passes just request object.

feat(utils/pagination): Add `extra_context` in pagination class

---

{{cookiecutter.github_repository}}/fabfile.py

- It depends on django-extensions and doesn't really solve any problem in a
meaningful ways.
- Most of the developers use runserver and this really avoid any inconsistency
- It's doesn't really well with devcargar (used in auto-reloading)
Revert back to use `runserver`
Nope

fix(fab): use `runserver` instead of 'runserver_plus'

---

CHANGELOG.md
{{cookiecutter.github_repository}}/.travis.yml

Faster installation of pip packages
pip-accel caches these packages
none that are apparent, used in previous projects.

feat(travis.yml):add pip-accel

---

CHANGELOG.md
README.md
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/settings/development.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/templates/base.html
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/urls.py

It makes development with html, js, css, scss way much faster, without the need of any browser plugin. 
By adding a non-obtrusive, easy to install livereload functionality, all in python. Works great with django-compressor. 
Probably you would like to remove this if any other liveloading tool is used. e.g. grunt, gulp.

Enable livereload of frontend pages/assets in Development

---

CHANGELOG.md
README.md
cookiecutter.json
hooks/post_gen_project.sh
{{cookiecutter.github_repository}}/.travis.yml
{{cookiecutter.github_repository}}/docs/backend/server_config.md
{{cookiecutter.github_repository}}/fabfile.py

When it's known for sure that the site won't be deployed to any ubuntu based
machines, having the provisioning script, it's related fab commands and docs
is not very optimal.
If the ansible is required at a later stage then it's needs to be manually. The
user can use the same cookiecutter while saying `add_ansible=y` and then copy
over the required bits.

feat(cookiecutter): make generation of ansible related stuff optional

---

CHANGELOG.md
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/exceptions.py

Django 404, ValidationError, PermissionDenied were not following defined error formatting.
It fixes its formatting to match the existing.
No

fix(exceptions): fixed django exceptions error handling format.

---

CHANGELOG.md
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/development.py
{{cookiecutter.github_repository}}/settings/production.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/urls.py

We may not want to give browsable api interface on staging or prod environments.
We now have a setting variable that allows us to enable the browsable api on any of the environment. By default the browsable api would be turned off for all the environment except local development environment.
No

chore(api-settings): remove browsable api from prod environments

---

{{cookiecutter.github_repository}}/Vagrantfile

So that the compilation of libraries like lxml succeed without
any issue.

Update virtualbox config to use min 1GB RAM, default is 512MB

---

{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/urls.py

Customizing admin url between different environment is not possible with current hardcoded path.
Allow customizing admin url path via environment variable.
No. The default is the same.

feat(django/admin): Allow customizing admin url path via environ

---

CHANGELOG.md
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/tests/factories.py

* Why was this change necessary?
Simplifies writing factories and prevents duplication of model defination.
* How does it address the problem?
django-dynamic-fixtures provies two methods `G/get` and `N/new` that provides defaults
for almost all the model field types and default rules for custom field types can
be easily setup.
* Are there any side effects?
Not for any new projects, just that devs need to be familiar with DDF to be utilize
it at best! ;)

refractor(tests): use django-dynamic-fixtures instead of factory-boy

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/settings/common.py

Currently there is no way we can log the things and check if somethings goes wrong on the servers
This pull request adds the logging support for django, All the logs are send to the standard output. Also this pull request add support for request ids. Unique Request ids are generated for each and every request, which makes debugging in production easier.
Nothing as of now.

Add support for `Logging` (#169)

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/production.txt

*Major changes*
Django==1.9.8
djangorestframework==3.4.0
whitenoise==3.2
Pillow==3.3.0
boto==2.42.0
Not upgrading flake8 to 2.6 as it has some breaking changes

Update requirements to latest.

---

cookiecutter.json
{{cookiecutter.github_repository}}/docs/backend/server_config.md
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/production.py

- Don't provide any default value, it must need to be set per environment.
- Ensures bug free handover to client, where we forget to change remove the value.

Make sure DJANGO_ADMINS is set via environment variable in production

---

{{cookiecutter.github_repository}}/setup.cfg

removed warning in CI environment. 
Changing [pytest] to [tools:pytest] removed this warning. Also in Pytest 4.0 we need to have setup.cfg as per this format as the current format will be deprecated. 
No. The sample project tests passed successfully on my CI. 
- changed [pytest] to [tool:pytest] in setup.cfg to ignore `WC1 None` warning

chore(pytest-warning): removed WC1 pytest warning in CI

---

{{cookiecutter.github_repository}}/package.json

#> Why was this change necessary?
postcss-cli required latest version of node.
Resolves the issue.
- Upgrade to node version to 6.4.0 from 5.11.0
postcss-cli required the latest version of node.

Update Node Dependency

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/production.txt

Major releases:
pytest-django==3.0.0 (http://docs.pytest.org/en/latest/changelog.html)
python-dotenv==0.6.0 (https://pypi.python.org/pypi/python-dotenv/0.6.0#changelog)
django-log-request-id==1.3.1 (https://github.com/dabapps/django-log-request-id/commits/master)
Minor release:
django-extensions==1.7.4
djangorestframework==3.4.6
whitenoise==3.2.1
Pillow==3.3.1
pytest-pythonpath==0.7.1

Update requirements to latest stable.

---

CHANGELOG.md
{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/main.yml

Current version of certbot-auto was doesn't work in non-interactive mode if the
flag is not provided. This commit fixes it.

Fix letsencrtypt, make certbot-auto run in non-interactive mode

---

{{cookiecutter.github_repository}}/provisioner/roles/project_data/meta/main.yml

Was a missout when switching to ubuntu 16.
Added the missing file that setups nodejs
nope

fix(django_compressor): Fix issues with nodejs setup django compressor

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/main.yml

Fixes the condition that doesn't generate dhparam in nginx module
removed the incorrect condition 
None

fix(nginx_role): Fix the ansible condition to generate dhparam file

---

CHANGELOG.md
{{cookiecutter.github_repository}}/settings/testing.py

Previously its not loading `.env` file for `py.test` run
It'll load in `settings/testing`  using `python-dotenv`
No.

Load .env for running Py.test

---

{{cookiecutter.github_repository}}/requirements/production.txt
{{cookiecutter.github_repository}}/settings/production.py

In order to setup s3 in mumbai region aka ap-south-1 as the static / media backend
the project would have to use `storages.backends.s3boto3.S3Boto3Storage`, which in
turn would need boto3 instead of boto and the newest version of django-storages.
django-storages-redux has not been updated since Jan 2016 and has been releasing on
pypi as django-storages since Feb 2016 when it became the official successor of the
repository it was a fork of[1].
[1] https://github.com/jschneier/django-storages#history
[2] https://github.com/jschneier/django-storages/issues/28#issuecomment-265876674
Trouble uploading to s3 in mumbai region
adds required environment variables and upgrades boto3 and django-storages to their latest versions.
> …

enable support for newer aws regions

---

{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml

fixes #215
Project dir is owned by completely different user and uwsgi process is run by other. So if we are using local media files upload, it create problems
We are giving uwsgi user group, `www-data` ownership of project dir
No

fix(provisioner/project): Give uwsgi group the ownership of project dir

---

{{cookiecutter.github_repository}}/settings/development.py

Signed-off-by: Abhishek Kumar Singh <abhishek4bhopati@gmail.com>
It'll allow any host to access server running under vagrant box.
Adding `ALLOWED_HOSTS` to `*`
No

Added `ALLOWED HOSTS` and updated `INTERNAL_IPS` list for vagrant run.

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/handlers/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/main.yml

While deploying code, we do not verify nginx config and try to reload straight away. This creates problems.
Before reloading nginx, we not have a hook to ensure nginx config is valid.
No

chore(ansible/nginx): Check nginx config before reload/restart

---

CHANGELOG.md
hooks/post_gen_project.sh
{{cookiecutter.github_repository}}/README.md
{{cookiecutter.github_repository}}/setup.cfg

Use simplified bumpversion rules, remove requirement of intermediate release tags e.g. `0.1.0-dev`.

Update bumpversion logic to make it simple

---

{{cookiecutter.github_repository}}/settings/common.py

Redis database name should be provided in the .env and not hard-coded.

fix(settings/celery): update CELERY_BROKER_URL to properly respect REDIS_URL

---

CHANGELOG.md
{{cookiecutter.github_repository}}/docs/api/errors.md
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/exceptions.py

fix #234 
Currently the custom exception handler does not parse the nested serializer errors properly.
It will parse the nested serializer errors upto 10 level depth as DRF supports maximum 10 depth.
No

feat(exceptions): handle nested serializer errors in our exception handler

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/main.yml

nginx doesn't get reloaded reliably. 
Use '--renew-hook' instead of shell chaining, which might fail due to wrong
exit code from "certbot-auto" command
None.

fix(nginx/letsencrypt): ensure nginx is reloaded after renewal of cert

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt

Duplicate entry in common and development files.
Versatileimagefield added to requirements as it is being used in base imagemixin.
Removes the older version from development file.
no
fixes #243

fix(requirements): remove duplicate requirement

---

{{cookiecutter.github_repository}}/docs/backend/coding_rules.md

Fixes coding guidelines according to Python3 and other typos.
Use `__str__` in guidelines instead of `___unicode___` for supporting Python3.
None.

Minor spell fixes in coding_rules.md

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/defaults/main.yml

nginx above 1.9 supports http2 by default, this is required to enable the same.
enhancement. http2 among other things, makes only one request to the server reducing the overhead of multiple calls. 
though minor will effect the performance of the application.
enables http2
browsers that do not support http2 will be able to work with http1.1, so no side effects.

enable http2

---

{{cookiecutter.github_repository}}/provisioner/roles/project_data/templates/django.uwsgi.ini.j2

These errors occur when network connection is abruptly dropped by
nginx(by browser)  and uwsgi hasn't yet responded.
Sentry catches them as uwsgi raises. We don't need this error level
add your text here...
add your text here...
add your text here...

uwsgi: Ignore os write errors in django-uwsgi

---

{{cookiecutter.github_repository}}/.env.sample
{{cookiecutter.github_repository}}/docs/backend/server_config.md
{{cookiecutter.github_repository}}/settings/production.py

The default config is too permissive with `*`. Leading to people forget adding ALLOWED_HOSTS often. 
It will raise a `ImproperlyConfigured` like many other settings already does already and server will refuse to star.
Nope, just requires one time putting up ALLOWED_HOSTS during server setup.

settings: make putting up ALLOWED_HOSTS compulsory in production

---

CHANGELOG.md
{{cookiecutter.github_repository}}/fabfile.py
{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.443.conf.j2
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt

Keeps the documentation in sync with the codebase deployed on each of the environment. Also there is no need to deploy the docs separately. Now, if using ansible/nginx setup, the docs are available at `/docs` url for each of the domain. 
Documentation sometimes remain outdated. It's hard to know, what deployed on dev vs qa vs production environment. Now, by visiting at the `/docs/` url of each environment, it possible to know what deployed and what's not.
The old deployment on gh-pages, is still possible with `mkdocs gh-pages`, and if not using ansible, `fab deploy_docs` works the old way.

Add automatic documentation build when using ansible and make it available at `/docs/` urls

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.443.conf.j2
{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.80.conf.j2

Add present the servers doesn't listen if the server IP is IPv6. 
Support of IPv6 enabled in nginx which is the top-level proxy for all the incoming requests to server.
nope

nginx: enable ipv6 support

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/nginx.conf.j2

Missing encoding info in the responses.
The ngx_http_charset_module module adds the specified charset to the “Content-Type” response header field. In addition, the module can convert data from one charset to another, with some limitations:
- conversion is performed one way — from server to client,
- only single-byte charsets can be converted
- or single-byte charsets to/from UTF-8.
https://nginx.org/en/docs/http/ngx_http_charset_module.html
If the application is intensionally has different encoding that utf-8, then this value should be changed to reflect that.

nginx: enable ngx_http_charset_module to add default utf-8 encoding to content-type headers

---

CHANGELOG.md
{{cookiecutter.github_repository}}/provisioner/roles/celery/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/celery/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/celery/templates/celery.service.j2
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/site.yml

Fixes celery beat schedule file path on servers.
Also makes celery roles consistent in provisioner across deployments.
Currently, scheduler file is spawned in the source code dir. This poses problems on server, since we only want to give read access to the source code.
The PR separates out the schedule file to a separate dir where the state of tasks is maintained.
None.

fix(celery): celery beat scheduler issue

---

CHANGELOG.md
{{cookiecutter.github_repository}}/settings/production.py

- 
Empty region generate error in s3 url.
Null region avoid region configuration in S3 url.
No

fix(settings): make s3 region default null

---

CHANGELOG.md
{{cookiecutter.github_repository}}/settings/common.py

At this point only Exceptions are captured by Sentry. It would be good idea to capture `ERROR` logs too.
Capture `ERROR` level logs for Sentry.
None.

feat(logging): Add Error level logging to sentry mails

---

{{cookiecutter.github_repository}}/provisioner/roles/celery/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/letsencrypt.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.443.conf.j2

- Install nginx full
- Move nginx configuration to variables to avoid duplication
- Use certbot instead of certbot-auto
- make celery installation without sudo
Fix nginx reload issue after letsencrypt renew job.
Changed the renew job and use the official certbot configuration.
No

fix(ansible): add official nginx and certbot repo and configuration

---

{{cookiecutter.github_repository}}/.travis.yml

Travis builds are failing. `pip-accel` is not needed. We can just use `pip`.
Travis builds no longer fails.
None.

feat(.travis.yml): Removes pip-accel

---

.gitignore
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/models.py

We use python 3 and flake8 currently breaks with static hinting syntax in python 3 code.
Use flake8-mypy drop-in plugin for flake8 to add support for mypy checks.
🙅‍♂️

Add support for static type hinting check via flake8-mypy

---

{{cookiecutter.github_repository}}/.travis.yml

Postgis addon not included with new travis environment and pip accel was causing issue with ansible installation
added postgis addon installation and removed pip accel as pip is fast now
No

update postgresql, add postgis addon and remove pip accel

---

{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/services.py

The unused import causes flake8 error during the dev CI testing
By removing the unused import CI and other test run fine. 
Nothing since I haven't encountered anything.

chore(users/services.py): removed unused import

---

{{cookiecutter.github_repository}}/provisioner/hosts
{{cookiecutter.github_repository}}/provisioner/roles/nginx/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/postgresql/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml

`environment` as a var name is restricted in ansible.
http://docs.ansible.com/ansible/latest/playbooks_variables.html#magic-variables-and-how-to-access-information-about-other-hosts
Renamed the environment var to deploy_environment
No.

Renamed environment var to deploy_environment

---

{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/__init__.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/auth/__init__.py

removing utf-8 at the top of the file caused `W391 blank line at end of file in user app` PEP8 errors
It adds a comment stating the purpose of the folder.
No.

fixing pep8 W391 blank line at end of file in user app

---

CHANGELOG.md
{{cookiecutter.github_repository}}/settings/common.py

More info at https://mounirmesselmeni.github.io/2014/11/06/date-format-in-django-admin/
It's not always clear in admin, the datetime display belongs to which timezone. 
Add the timezone details in the time displayed, in list view and elsewhere.
No

Add timezone information to datetime displayed.

---

CHANGELOG.md
cookiecutter.json
{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/nginx.conf.j2
{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.443.conf.j2
{{cookiecutter.github_repository}}/provisioner/vars.yml
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/development.py
{{cookiecutter.github_repository}}/settings/production.py
{{cookiecutter.github_repository}}/wsgi.py

https://github.com/Fueled/django-init/issues/277
- Adds `enable_whitenoise` option to cookiecutter which defaults to `no`. 
- Falls back to manifest static storage.
- Enables gzip compression on nginx if whitenoise is not enabled.
- Adds static and media routes.
Yes. As listed above.

Make whitenoise optional

---

{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/production.py

This refactors the django-sites used in the project to have a `current` site pointing to current backend server. Also fixes the `MEDIA_URL` to have absolute URL from env through django-sites
None.

fix(settings): Fix django-sites config along with MEDIA_URL

---

CHANGELOG.md
README.md
cookiecutter.json
hooks/post_gen_project.sh
{{cookiecutter.github_repository}}/.travis.yml
{{cookiecutter.github_repository}}/circle.yml
{{cookiecutter.github_repository}}/docs/backend/server_config.md
{{cookiecutter.github_repository}}/settings/production.py

fueled does not use heroku for deploying its apps anymore. 
heroku deployment made optional to keep everyone happy
Adds enable_heroku_deployment option to the cookiecutter

Optional heroku support

---

CHANGELOG.md
README.md
hooks/post_gen_project.sh
{{cookiecutter.github_repository}}/.travis.yml
{{cookiecutter.github_repository}}/circle.yml
{{cookiecutter.github_repository}}/fabfile.py
{{cookiecutter.github_repository}}/settings/__init__.py
{{cookiecutter.github_repository}}/settings/testing.py

The new `pytest` is preferred over old `py.test` https://stackoverflow.com/a/41893170/3535547
The `py.test` can potentially be deprecated in future, so it is best to use `pytest`
None.

fix(tests): Use pytest instead of py.test

---

CHANGELOG.md
{{cookiecutter.github_repository}}/provisioner/roles/celery/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/celery/templates/celerybeat.service.j2

Celery beat does not expect `start` or `stop` argument.
Fixing celery beat to run as a service
None.

fix(celery-beat): Fix celery beat service

---

{{cookiecutter.github_repository}}/provisioner/roles/common/tasks/main.yml

We are trying to build the uwsgi plugin before installing it.  
Removes the unnecessary task. We install the plugin in the uwsgi setup task file also.
No.

feat(provisioner) - remove extra uwsgi build from common tasks

---

CHANGELOG.md
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/models.py

Fixes naming for `created` and `modified` to `created_at` & `modified_at` respectively in `TimeStampedUUIDModel`
`created` & `modified` aren't explicitly enough that they actually store `DateTimeField`.
None.

fix(base/models): Fix naming in TimeStampedUUIDModel

---

CHANGELOG.md
run_test.sh
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/auth/api.py

Currently there can be errors due to flake8, as in the builds we're not testing if the code follows standards.
Added flake8 command in `run_test.sh`. Also, `run_test.sh` has been modified to give a non-zero exit status if any of the commands fail.
None

Add flake8 in travis builds of django-init

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/main.yml

- Since state=installed will be removed in version 2.9 of ansible hence it make sense to do the change
- by changing the variable state=present. The warning nullifies
No. Tried with my own setup. :)

chore(provisioner/roles/nginx): remove ` State 'installed' is deprecated.` warning

---

{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/celery.py

register_signal tries to instantiate the sentry client again exceeding the maximum recursion depth.
register_signal and register_logger_signal have to be imported explicitly.
This PR reverts the celery import cleanup to fix this.

hotfix - revert celery import cleanup

---

{{cookiecutter.github_repository}}/settings/common.py

Other parameters for supporting translation and internationalization are already there in the settings. But for multilingual support, LocaleMiddleware is needed to convert the response in the requested language.
LocaleMiddleware is needed to convert the response in the requested language.
None.

Add LocaleMiddleware in settings to add multi-language support

---

CHANGELOG.md
{{cookiecutter.github_repository}}/provisioner/roles/common/files/pip.conf
{{cookiecutter.github_repository}}/provisioner/roles/common/files/pydistutils.cfg
{{cookiecutter.github_repository}}/provisioner/roles/common/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml

Some cloud providers like Alibaba cloud uses default pypi and easy_install mirror set to aliyum on booting up the ECS instance.
However, the deployment will fail, since for `easy_install`,  from `.pydistutils.cfg`, the `virtualenv` is not properly made (without any `bin` folder, `activate` script etc.)
Also, the `.pip/pip.conf` ensures that the global url for pypi mirror for fetching packages from requirements is actual python.org server for reasons mentioned above.
Apart from these changes, I've added a `compilemessages` command, so that the static messages are translated on every deployment if available.
Reasons mentioned above.
None.

feat(localization): Add compilemessages & fix default pypi mirror

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/nginx.conf.j2

Just a minor typo fix in one of the comments in `nginx.conf`
None

fix(provisioner/nginx.conf): Minor typo fix

---

{{cookiecutter.github_repository}}/requirements/common.txt

Celery 4.1.0 is breaking because it includes an incompatible kombu version.
This PR upgrades celery to 4.1.1 to avoid it.
Yes. Celery version is upgraded.
add your text here...

fix(system) - Update celery to avoid kombu incompatibility

---

{{cookiecutter.github_repository}}/mkdocs.yml

WARNING -  Config value: 'pages'. Warning: The 'pages' configuration option has been deprecated and will be removed in a future release of MkDocs. Use 'nav' instead.
Aborted with 1 Configuration Warnings in 'strict' mode!
Changing `pages` option to `nav` in `mkdocs.yml` clears the error.
No.

change `pages` option in `mkdocs.yml` file to `nav`

---

{{cookiecutter.github_repository}}/tests/integration/test_auth.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/api/routers.py

DynamicListRoute has been deprecated since DRFv3.8.0 ( #315 ).
DynamicListRoute has been replaced with DynamicRoute in `base/api/routers.py`
To use DynamicRoute one has to declare viewset action with `@action` decorator. So, all the extra viewset actions should be refactored to make it work.

fix(base/api/routers): Deprecating DynamicListRoute

---

{{cookiecutter.github_repository}}/requirements/development.txt

Travis builds are failing since one of the packages installed downgrades to pytest 3.3 which uses a deprecated api of attrs.
It pins the pytest version to the latest one.
None apart from pinning down pytest version.

chore(requirements) - pin pytest version to avoid attrs incompatability

---

{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml

env deploys fail after compilemessages was added to project_data role
installs gettext required by compilemessages
Yes. Installs gettext if not present. This is an additional dependency.

fix(provisioner) - install gettext for compilemessages

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/api_urls.py

To update the tool to support the latest version of Django and DRF.
Upgrade Django to `2.1.4` and DRF to `3.9.0` and prevent deprecation warning in `api_urls` by using `basename` in favor of `base_name`.
None

chore(requirements): Upgrade Django=2.1.4 & DRF 3.9.0

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/production.txt

Keeping django-init upto date for new projects.
Non-breaking updates have been made.
None.

chore(requirements): Update requirements to latest stable

---

{{cookiecutter.github_repository}}/requirements/common.txt

Temporary fix for #330
To avoid error on swagger index page saying `rest_framework_swagger/base.html` Template not found
Swagger works again for the newly spawned projects.
None

chore(requirements): Downgrade Swagger to 2.1.2 from 2.2.0

---

{{cookiecutter.github_repository}}/provisioner/roles/redis/tasks/main.yml

Avoid deprecation warning for `installed` state.
`[DEPRECATION WARNING]: State 'installed' is deprecated. Using state 'present' instead. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.`
Updates state `installed` to `present` for ansible task.
None.

fix(provisioner/roles/redis): Update ansible state from installed to present

---

{{cookiecutter.github_repository}}/settings/development.py

Why was this change necessary?
django-init was unable to serve media files. This addresses #323.
How does it address the problem?
MEDIA_URL configuration is added to support serving media file.
Are there any side effects?
None.

fix(settings/dev): Added MEDIA_URL configuration

---

{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/production.py

Add `access-control-allow-origin` to `CORS_ALLOW_HEADERS` to allow pre-flight requests.
Added to support AJAX pre-flight requests.
None.

fix(settings): Add 'access-control-allow-origin' to CORS headers

---

{{cookiecutter.github_repository}}/settings/common.py

Travis builds are failing on flake8 due to "is not" operator for string comparison.
Travis error message:
```
./settings/common.py:474:27: F632 use ==/!= to compare str, bytes, and int literals
```
No.

refactor(settings/common) - do string comparison using "!=" instead of "is not"

---

{{cookiecutter.github_repository}}/settings/common.py

Fix `IS_RAVEN_INSTALLED`
Fix `IS_RAVEN_INSTALLED`
None

fix(settings/common): Set-up IS_RAVEN_INSTALLED variable

---

{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/celery.py

Generator leaves a raven import in `celery.py` when sentry is not being used
Adds the conditional for when to keep the import
Yes.

fix - remove raven import when sentry is not being used

---

{{cookiecutter.github_repository}}/docs/api/endpoints.md
{{cookiecutter.github_repository}}/docs/backend/coding_rules.md
{{cookiecutter.github_repository}}/docs/backend/server_config.md
{{cookiecutter.github_repository}}/docs/index.md

Documentation uses a mix of `**` or `__` to bolden text. 
Most of the files used the `__` syntax. This replaces `**` with `__`.
No

docs - make markdown bold syntax in docs consistent

---

{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/celery.py

Imports weren't sorted in celery.py file.
Sort imports
None

fix(celery.py): Sort import for celery

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/templates/rest_framework_swagger/index.html

Keeping our project dependency upto date.
2.2.0 is a breaking change and this version doesn't include base.html and some
of the customizations we were doing ealier aren't available in the version. So
it's removed for simplicity.
The project name displayed in the nav bar won't be available, also the UI of new
swagger is changed from previous one.
closes #330

feat(requirements): upgrade django-rest-swagger to 2.2.0

---

{{cookiecutter.github_repository}}/requirements/common.txt

Got a security alert from github
Upgrades to latest version
No. Version upgrade is backwards compatible

chore - upgrade django rest framework to latest

---

{{cookiecutter.github_repository}}/.env.sample
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/production.txt

To keep things upto date. Django will be updated in another PR.
...
django-cors-headers now recommends domains with schemes, so example is updated
add your text here...

chore(deps): update requirements to it's latest stable (except django)

---

{{cookiecutter.github_repository}}/requirements/development.txt

CVE-2019-3828
critical severity
Vulnerable versions: < 2.5.15
Patched version: 2.5.15
Ansible fetch module before versions 2.5.15, 2.6.14, 2.7.8 has a path traversal vulnerability which allows copying and overwriting files outside of the specified destination in the local ansible controller host, by not restricting an absolute path.
CVE-2018-10855
high severity
Vulnerable versions: >= 2.5.0, < 2.5.5
Patched version: 2.5.5
Ansible 2.5 prior to 2.5.5, and 2.4 prior to 2.4.5, do not honor the no_log task flag for failed tasks. When the no_log flag has been used to protect sensitive data passed to a task from being logged, and that task does not run successfully, Ansible will expose sensitive data in log files and on the terminal of the user running Ansible.
> …

upgrade(requirements/dev): Upgrade ansible 2.5.0 -> 2.5.15

---

{{cookiecutter.github_repository}}/settings/common.py

Also, remove unused 'null' formatter
The runserver logs had a lot of info due to `complete` formatter userd.
Use special formatter provide django.utils.logging to format the request log from runserver.
Nope.

fix(logger): use ServerFormatter for request logs in runserver

---

{{cookiecutter.github_repository}}/provisioner/roles/celery/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/celery/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/celery/templates/celerybeat.service.j2

When the server gets restarted, /var/run/celery doesn;t exist and server is on 100% CPU usage. 
systemd services creates the directly when started and removes when its stopped.
Not known as of now

Fix celerybeat run dir

---

{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/urls.py

- Makes thing more clean.
- 'url()' is depreciated, so it's better to remove it.
- Use 'django.urls' instead of 'django.conf.urls'
Use 'path()' and 're_path()' where necessary. 
Not that i'm aware of.

refractor(urls): update urls.py to use new 'path' and 're_path'

---

CHANGELOG.md
{{cookiecutter.github_repository}}/provisioner/roles/celery/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/celery/templates/celery.service.j2

The default concurrency was set to 4 which is generally too high for dev/QA instances.
Celery automatically configures the concurrency depending on the number of CPUs available if omitted and this PR does that. https://docs.celeryproject.org/en/latest/userguide/workers.html#concurrency
nope. The concurrency can be added back as needed.

Update celery concurrency to default to number of CPUs

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/defaults/main.yml

Nginx allows automatic configuration of its workers based on the no. of available CPUs on the deployed, this will allow Nginx to run at its optimal performance in a prod like environment. 
Let Nginx decide and configure it's number of workers based on the no. of available CPUs https://nginx.org/en/docs/ngx_core_module.html#worker_processes
No.

fix(nginx): let nginx configure it's no. of workers based on no. of CPUs

---

{{cookiecutter.github_repository}}/provisioner/hosts
{{cookiecutter.github_repository}}/provisioner/roles/celery/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.443.conf.j2
{{cookiecutter.github_repository}}/provisioner/roles/postgresql/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/uwsgi-setup.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/templates/django.logrotate.j2
{{cookiecutter.github_repository}}/provisioner/roles/project_data/templates/django.uwsgi.ini.j2

To simplify cookiecutter naming and folders. 
make the log directories consistent.
The proposes new directory paths, which might not be very obvious of devs already used to current directories.

refractor: improve variable naming and standardize log and venv dirs

---

CHANGELOG.md

Changelog has some inconsistencies. This cleanup and maintain standard size subheadings. It also ensures that all contributors have a link to their respective profile as the changelog for 2.x tries to accomplish.
Cleanup the changelog.
None.

fix(changelog): Cleanup changelog and add links for contributors

---

CHANGELOG.md
README.md
{{cookiecutter.github_repository}}/.editorconfig
{{cookiecutter.github_repository}}/.pre-commit-config.yaml
{{cookiecutter.github_repository}}/CONTRIBUTING.md
{{cookiecutter.github_repository}}/fabfile.py
{{cookiecutter.github_repository}}/manage.py
{{cookiecutter.github_repository}}/settings/__init__.py
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/development.py
{{cookiecutter.github_repository}}/settings/production.py
{{cookiecutter.github_repository}}/settings/testing.py
{{cookiecutter.github_repository}}/setup.cfg
{{cookiecutter.github_repository}}/tests/conftest.py
{{cookiecutter.github_repository}}/tests/factories.py
{{cookiecutter.github_repository}}/tests/integration/test_auth.py
{{cookiecutter.github_repository}}/tests/integration/test_current_user_api.py
{{cookiecutter.github_repository}}/tests/integration/test_site_pages.py
{{cookiecutter.github_repository}}/tests/unit/test_api_versioning.py
{{cookiecutter.github_repository}}/wsgi.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/api_urls.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/api/schemas.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/views.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/urls.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/auth/backends.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/migrations/0001_initial.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/migrations/0002_auto_20171024_1200.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/models.py

To keep the code styling standard for every developer. 
Using black to format code, black is added to pre-commit so the code is always formatted before making a commit.
There could be cases that a dev doesn't want a restrictive formatting. I think having a tool to format the code for everyone wins. Readability and code-reviews matter.

Add black in pre-commit and also formatted exiting code as per black

---

{{cookiecutter.github_repository}}/docs/api/0-overview.md
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/auth/backends.py

`Token` scheme currently used is not the HTTP auth standard
https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#Authentication_schemes
- Changes to the standard Bearer auth scheme.
- Adds documentation for authentication
Yes. Clients for the new projects would now have to authenticate using the Bearer scheme instead of the token one.

feat(users/auth) - Use standard Bearer authentication scheme

---

{{cookiecutter.github_repository}}/requirements/common.txt

updated django, drf and django cors headers
drf 3.10 has better affordances for auto-generated docs. So, this PR is like a pre-cursor for that change
No

chore - update django, django rest framework, cors headers

---

{{cookiecutter.github_repository}}/requirements/common.txt

Upgrade django-versatileimagefield to 1.11
Upgrade django-versatileimagefield to 1.11
None.

chore(): Upgrade django-versatileimagefield to 1.11

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/letsencrypt.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.443.conf.j2
{{cookiecutter.github_repository}}/provisioner/roles/nginx/templates/site.80.conf.j2

Incorporate changes from https://github.com/Fueled/django-init/issues/380 
This also moves the letsencrypt cron task to letsencrypt.yml

Fix typo of variable "letsencrypt_challenge_root"

---

{{cookiecutter.github_repository}}/requirements/common.txt

Recently all Django management commands started breaking giving following error: 
```
Traceback (most recent call last):
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/config.py", line 388, in resolve
found = getattr(found, frag)
AttributeError: module 'log_request_id' has no attribute 'filters'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/config.py", line 390, in resolve
self.importer(used)
ModuleNotFoundError: No module named 'log_request_id.filters'
The above exception was the direct cause of the following exception:
Traceback (most recent call …
```

chore(): Update django-log-request-id to 1.4.0

---

{{cookiecutter.github_repository}}/provisioner/roles/nginx/defaults/main.yml

this typo was fixed in in our tasks but not in the defaults. Hence, our provisioner scripts are failing now.
Fixes the typo in defaults nginx configuration as well
Nope. I have verified that we can succesfully configure a server now.

fix(provisioner) - typo for letsencrypt_challenge_root in defaults

---

{{cookiecutter.github_repository}}/requirements/development.txt

bumpversion is no longer actively maintained. There are some discussions going on to get bump2version's updates to more users by possibly merging the two projects.
https://github.com/c4urself/bump2version/issues/86
Uses bump2version which is a drop in replacement
No.

chore - use actively maintained bump2version instead of bumpversion

---

{{cookiecutter.github_repository}}/settings/common.py

The base project generated errors out for swagger ui view at `/api-playground` with the error `'AutoSchema' object has no attribute 'get_link'`
Fix specified here on this issue:
https://github.com/encode/django-rest-framework/issues/6809
No

fix(swagger) - include default schema class settings for swagger ui

---

{{cookiecutter.github_repository}}/provisioner/vars.yml

ubuntu 18.04 comes with python3 as default and ansible look for python2 and fails. To fix that we have to install python2 on the server or create an alias of python to python3
This change will tell ansible to look for python3 instead of python2 by default
It won't work on old OS which have python2 as default, to make that work we have to remove this setting

set python3 as default interpretor for ansible

---

{{cookiecutter.github_repository}}/provisioner/roles/postgresql/tasks/main.yml

With default interpreter switched to python3, install python3 psycopg2 instead of python2
Installs python3 psycopg2
Yes. psycopg2 will no longer be available for python 2

feat(provisioner) - install python3 psycopg2

---

.travis.yml
{{cookiecutter.github_repository}}/.travis.yml

All the recent Travis CI builds on django-init are breaking and the master branch is also failing. Also, the projects generated through the cookiecutter will consequently have failed CI tests as the pytest wasn't able to connect to the Postgres database running within the docker container.
The Postgres is now installed directly on Travis and all the config are copied from Postgres 9 (which is installed by default) to Postgres 11. Given that now we've two different Postgres version on Travis, Postgres 11 will run on the next available port from the default port of 5432, which is 5433.
None.

fix(travis): Remove docker and install Postgres 11 directly on Travis

---

CHANGELOG.md
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/production.txt
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/production.py
{{cookiecutter.github_repository}}/settings/testing.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/exceptions.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/auth/utils.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/models.py

Updates cookiecutter template to support Django 3.x
Updates the version of various library and for the time being, add a patched version for django-sites.
None.

Add support for Django 3.x

---

{{cookiecutter.github_repository}}/requirements/common.txt

whitenoise tries to import django.utils.six which does not exist in django3 anymore.
resolves import error.
not in my knowledge.

upgrade whitenoise to work with django 3

---

.travis.yml
{{cookiecutter.github_repository}}/.travis.yml

Postgresql 11 is natively supported on bionic dist (Ubuntu 18), this removes the hackish code for setting up postgresql11 on travis.
I also enables postgis setup by default to be checked while running tests in this cookiecutter.
Update travis.yml to use standard installation config.
No.

Fix travis config for postgresql 11

---

{{cookiecutter.github_repository}}/tests/integration/test_auth.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/auth/serializers.py

The registration API didn't allow `first_name` and `last_name` to be saved.
The two fields have been added to the registration serializer.
None.

fix(users/serializers): Add first_name and last_name

---

CHANGELOG.md
hooks/post_gen_project.sh
{{cookiecutter.github_repository}}/.gitignore
{{cookiecutter.github_repository}}/bin/generate_db_schema.py
{{cookiecutter.github_repository}}/docs/index.md
{{cookiecutter.github_repository}}/mkdocs.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/main.yml
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/settings/development.py

It gives management & other team members better idea about current database schema
Gives everyone access of latest db schema
No

docs(): automate generating the latest db schema on deployment in docs

---

CHANGELOG.md
{{cookiecutter.github_repository}}/setup.cfg

Add default parameter to pytest while running test via cli so that the last failed
test are run first and then all the recently modified test are run in cronological
order.
This saves time running test as the failed test are run first or the recently modified. The failure is caught early, as the successful test or old tests are run later at the end.
Adds default argurements `--failed-first / --ff` and `--new-first / --nf`  to PyTest.
Not that I can think of. It changes the order of test execution. Currently the test are run as they are discovered on the disk, most likely alphabetically.

PyTest: Run failed test and then new test cases first

---

CHANGELOG.md
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/exceptions.py

The current exception formatter doesn't support displaying errors if the error
happened while validating any one of the child items in a ListField.
Currently for input:
```
{
"items": ["", ""]
}
```
The response is:
```
{
"error_type": "ValidationError",
"errors": [
{
"field": "items",
"message": 0
},
{
"field": "items",
"message": 1
}
}
```
After this fix, the output becomes:
```
{
"error_type": "ValidationError",
"errors": [
{
"field": "items",
"message": "Validation failed for one of the item in the list",
"errors": [
{
"field": 0,
"messsage": "This list may not be blank"
},
{
"field": 1,
"messsage": "This list may not be blank"
}
]
}
}
```

Fix formatting for failed validation for one of the items in ListField

---

{{cookiecutter.github_repository}}/.pre-commit-config.yaml

Python commit sorter is no longer necessary now that isort has its commit hook
Replaces with isort hook
Yes. We depend on isort repo now.

feat(system) - replace python commit sorter with isort hook

---

CHANGELOG.md
{{cookiecutter.github_repository}}/provisioner/roles/celery/tasks/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/tasks/uwsgi-setup.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/templates/uwsgi-emperor-init.d.j2

- The systemd refuses to start/stop uwsgi fails to start when the PID file world writeable,
the solution is to update the uwsgi init script to resuse the pid file which is created with
correct permssions instead of letting uwsgi-emperor create a world-writable pid file. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934731
- Celery services are already registered with systemd do when we invoke the ansible startup tasks
they fail, so those tasks are removed.

Fix the startup for celery and uwsgi-emperor on Ubuntu 20

---

{{cookiecutter.github_repository}}/docs/backend/api_mixins.md

Adds separate doc section for multiple serializer mixin in our documentation on api mixins.
No

docs - add documentation for MultipleSerializerMixin

---

{{cookiecutter.github_repository}}/tests/integration/test_auth.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/auth/serializers.py

There was no validation present during registration for `password` field. If the `first_name` or `last_name` will be more than 120 characters, instead of raising error, 500 server error will appear.
It adds `max_length` validation in `first_name` and `last_name` for registration serializer and makes sure to run password validations.
None.

fix(users/auth): Add validation for name & password in registration

---

{{cookiecutter.github_repository}}/.github/workflows/main.yml

Github Action CI won't trigger on PR for projects
Make CI trigger in project PRs.
None.

chore(): Add Github action CI on projects PR

---

{{cookiecutter.github_repository}}/provisioner/roles/project_data/defaults/main.yml
{{cookiecutter.github_repository}}/provisioner/roles/project_data/templates/django.uwsgi.ini.j2

As this almost always need to be tweaked in production depending the project requirement.
It introduces dynamic uwsgi workers via it's `cheaper` config.
No.

Tweak uwsgi config to allow for dyanamic number of workers

---

CHANGELOG.md
{{cookiecutter.github_repository}}/requirements/common.txt

Celery 4.4.7 had a regression introduced where with `--detach` and `--logfile`, it tries to find amqp although being explicitly instructed to connect with redis. More information here: https://github.com/celery/celery/issues/6370
It upgrades celery to 5.0.2 which no longer has this issue.
None that I'm aware of.

upgrade(requirements): Celery 4.4.7 -> 5.0.2

---

{{cookiecutter.github_repository}}/provisioner/roles/celery/templates/celerybeat.service.j2

the upgrade to celery 5 renders the previous command incompatible
uses the correct command invocation

fix(provisioner): celery beat start command for systemd service

---

cookiecutter.json
{{cookiecutter.github_repository}}/docs/api/0-overview.md
{{cookiecutter.github_repository}}/settings/common.py
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/base/api/pagination.py

Page number pagination creates issues on any customization
Cursor Pagination requires ordering on `timestamp` field which restricts its use everywhere. This change will add `Limit Offset` pagination as default and ask for `Cursor Pagination` on project generation.
No

feat() - make limit offset pagination default and add cursor pagination as optional

---

{{cookiecutter.github_repository}}/Makefile

* Upgrading pip
Pip version used in virtualenv is associated with
python version, and older python versions end up using outdated pip that
came packaged with it.
This results in a failure when installing some packages like
`cryptography`
* Installing wheel: Updated standard for python packaging.
Without wheel a few packages have to fallback on `setup.py`, throwing
this message:
> Using legacy 'setup.py install' for pkg-name, since package 'wheel' is not installed.
Wheel is also safer than setup.py and faster
Source: https://www.python.org/dev/peps/pep-0427/#rationale
Upgrades pip and installs wheel before any installation begins when doing `make install`
None

fix(installation): Upgrade pip before installing requirements

---

CHANGELOG.md
{{cookiecutter.github_repository}}/{{cookiecutter.main_module}}/users/auth/tokens.py

https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.rst#dropped-deprecated-verify-param-in-jwtdecode
Makes the algorithm explicit while encoding and decoding the token
No.

fix(users/auth): pyjwt requires the algorithm when calling decode()

---

CHANGELOG.md
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/docs.txt
{{cookiecutter.github_repository}}/requirements/production.txt

Note: Ansible not updated.
- Django updated to 3.1.x from 3.2.4 [changelog](https://docs.djangoproject.com/en/3.2/releases/3.2/)
- python-dotenv updated to 0.19.0 from 0.17.1 [changelog](https://github.com/theskumar/python-dotenv/blob/master/CHANGELOG.md)
- whitenoise updated to 5.3.0 from 5.2.0 [changelog](http://whitenoise.evans.io/en/stable/changelog.html)
- psycopg2-binary updated to 2.9.1 from 2.8.6 [changelog](https://www.psycopg.org/docs/news.html#what-s-new-in-psycopg-2-9)
- Pillow updated to 8.3.1 from 8.2.0 [changelog](https://pillow.readthedocs.io/en/stable/releasenotes/8.3.1.html)
- django-versatileimagefield updated to 2.1 from 2.0
- celery updated to 5.1.2 from 5.1.0
- mkdocs-material updated to 7.2.2 from 7.1.8
- iSort update to 5.9.3 …

Upgrade python dependencies to latest

---

{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt
{{cookiecutter.github_repository}}/requirements/production.txt
{{cookiecutter.github_repository}}/settings/common.py

- Fixes Pillow [CVE-2021-23437](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-23437) and Django [timezone regression](https://docs.djangoproject.com/en/3.2/releases/3.2.7/)
- Use unix socket for postgres connection by default
- Add flake8 back(removed in 5648a36ff0369297ca1e044b32e494422c887008)

Upgrade python libraries to thier latest patches

---

{{cookiecutter.github_repository}}/provisioner/roles/common/defaults/main.yml
{{cookiecutter.github_repository}}/requirements/common.txt
{{cookiecutter.github_repository}}/requirements/development.txt

Security vulnerabilities were found in celery 5.2.1 and ansible 2.2.1
Upgraded to celery 5.2.2 and ansible 4.2.0
None

Update packages: celery, ansible

---

{{cookiecutter.github_repository}}/pyproject.toml

The current version of black doesn't work with click 8.1.0. https://black.readthedocs.io/en/stable/change_log.html#id7
Upgrades to the version that fixes the problem
No

chore: upgrade black

---

.github/workflows/main.yml
{{cookiecutter.github_repository}}/.github/workflows/main.yml

`make lint` ran as part of CI/CD pipeline uses poetry to execute subsequent commands, but poetry is not installed -- which causes the pipeline to break.
It installs poetry first, before running `make lint` to ensure everything works in CI/CD flow.
None.

ci(github-actions): ensure poetry is installed lint action

---

{{cookiecutter.github_repository}}/docs/backend/coding_rules.md

The coding rules define class names to be camelCase instead of PascalCase which is a standard.
Fix the docs to reflect the correct case used in class names.
None.

docs(coding_rules): correct class names to be PascalCase

---

{{cookiecutter.github_repository}}/.github/workflows/main.yml
{{cookiecutter.github_repository}}/docs/backend/coding_rules.md

Currently github-actions uses legacy requirement file for dependency installation and not the updated poetry lock file. This legacy file can get out-of-date pretty quickly and a better way is to just use poetry to install dependencies and run tests.
Use poetry to install dependencies and run pytest.
None.

fix(github-actions): Use poetry to install requirements & run tests

---

{{cookiecutter.github_repository}}/README.md

The `--dev` flag in poetry is outdated. There is already a deprecation warning issued in poetry commands.
This updates the docs to reflect the poetry command with latest `--with dev` flag instead.
None.

docs(README): Update docs to drop legacy poetry command

---

{{cookiecutter.github_repository}}/pyproject.toml

There are couple of missing dependencies specifically for extensions related to mkdocs.
Add mkdocs dependencies to pyproject.toml directory for poetry to handle.
None.

fix(pyproject.toml): Add dependencies for mkdocs

---

README.md
cookiecutter.json
hooks/post_gen_project.sh
{{cookiecutter.github_repository}}/.envs/.dev/.env.sample
{{cookiecutter.github_repository}}/.envs/.local/.env.sample
{{cookiecutter.github_repository}}/README.md
{{cookiecutter.github_repository}}/compose/dev/django/Dockerfile
{{cookiecutter.github_repository}}/compose/dev/django/celery/beat/start
{{cookiecutter.github_repository}}/compose/dev/django/celery/flower/start
{{cookiecutter.github_repository}}/compose/dev/django/celery/worker/start
{{cookiecutter.github_repository}}/compose/dev/django/entrypoint
{{cookiecutter.github_repository}}/compose/dev/django/start
{{cookiecutter.github_repository}}/compose/dev/postgres/Dockerfile
{{cookiecutter.github_repository}}/compose/dev/postgres/maintenance/_sourced/constants.sh
{{cookiecutter.github_repository}}/compose/dev/postgres/maintenance/_sourced/countdown.sh
{{cookiecutter.github_repository}}/compose/dev/postgres/maintenance/_sourced/messages.sh
{{cookiecutter.github_repository}}/compose/dev/postgres/maintenance/_sourced/yes_no.sh
{{cookiecutter.github_repository}}/compose/dev/postgres/maintenance/backup
{{cookiecutter.github_repository}}/compose/dev/postgres/maintenance/backups
{{cookiecutter.github_repository}}/compose/dev/postgres/maintenance/restore
{{cookiecutter.github_repository}}/compose/local/Dockerfile
{{cookiecutter.github_repository}}/compose/local/entrypoint
{{cookiecutter.github_repository}}/compose/local/start
{{cookiecutter.github_repository}}/dev.yml
{{cookiecutter.github_repository}}/docs/backend/docker_setup.md
{{cookiecutter.github_repository}}/local.yml
{{cookiecutter.github_repository}}/pyproject.toml

Different services require lot of local setup and tweaking to work on different OS. The goal of this PR is to containerize the service and present to easily run all services with help of docker-compose.
This would dockerize the setup and run services like django, postgres, celery, flower in separate containers.
None.

chore: Add docker-compose to run all services through docker

---

{{cookiecutter.github_repository}}/compose/dev/django/Dockerfile
{{cookiecutter.github_repository}}/compose/dev/postgres/Dockerfile
{{cookiecutter.github_repository}}/compose/local/Dockerfile

If postgis is enabled, the docker setup does not work.
This PR enables use of postgis docker image for the database container & install GDAL for Django to communicate with the DB.
None.

feat(docker): Use GDAL/postgis when postgis is enabled

---

README.md
{{cookiecutter.github_repository}}/Makefile

The `--dev` option in `poetry export` command is deprecated. A warning is presented while using this option.
It updates the `poetry export` command to use the newer `--with` option.
None.

fix(Makefile): Update poetry export command to use --with option

---

{{cookiecutter.github_repository}}/compose/dev/django/start

When deployed on services like ECS, the logs aren't captured since they are not on the standard output and standard error streams.
Redirect output/error to std-out/std-err streams.
None.

fix(docker-start): Redirect access/error logs to std-out

---

{{cookiecutter.github_repository}}/compose/dev/postgres/Dockerfile

When not choosing to add Postgis, the resulting dev Dockerfile for Postgres ends up prefixed with `n`. This results in a 404 when trying to download the Docker image.
What happens:
```dockerfile
FROM npostgres:13
```
Expected:
```dockerfile
FROM postgres:13
```
Removes the template prefix of `cookiecutter.add_postgis` value.
No

fix(docker): Fixed an issue with the Postgres Docker image name
